name: Call Docker reusable workflow

on:
  push:

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  docker:
    uses: ./.github/workflows/docker-callable.yml
    secrets: inherit
    with:
      image-name: test
      push: true
