name: Lint files

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            json:
              - '**/*.json'

            markdown:
              - '**/*.md'

            renovate-config:
              - '/renovate.json'
              - '/default.json'

            workflow:
              - '.github/workflow/*'

      - uses: actions/checkout@v2

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
        if: steps.changes.outputs.renovate-config == 'true'

      # validates the default configuration included by all projects
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
        if: steps.changes.outputs.renovate-config == 'true'
        with:
          config_file_path: default.json

      - name: Install action-validator with asdf
        if: steps.changes.outputs.workflow == 'true'
        steps:
          - uses: asdf-vm/actions/install@v1
            name: Install action validator
            with:
              tool_versions: |
                action-validator 0.1.2

          - name: Lint Actions
            run: |
              find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) |\
                xargs -I {} action-validator --verbose {}
          
      - name: Validate Markdown file
        if: steps.changes.outputs.markdown == 'true'
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md "**/*.md"

      - name: Run JSON Lint
        if: steps.changes.outputs.json == 'true'
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
