name: Lint files

on:
  pull_request:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            json:
              - '**/*.json'

            markdown:
              - '**/*.md'

            renovate-config:
              - 'renovate.json'
              - 'default.json'

            workflow:
              - '.github/workflow/*'
    outputs:
      json: ${{ steps.changes.outputs.json }}
      markdown: ${{ steps.changes.outputs.markdown }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      workflow: ${{ steps.changes.outputs.workflow }}

  lint-renovate:
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@7ab3d8f19305664925f3e626580f075f14e40386 # v0.1.2
        
      # validates the default configuration included by all projects
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@7ab3d8f19305664925f3e626580f075f14e40386 # v0.1.2
        with:
          config_file_path: default.json

  lint-markdown:
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.markdown == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

      - name: Validate Markdown file
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md "**/*.md"

  lint-json:
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

      - name: Run JSON Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  lint-workflow:
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.workflow == 'true'
    container:
      image: rhysd/actionlint:1.6.22
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Validate Github workflows
        run: |
          mkdir .git
          actionlint -color
