name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 1
          ref: stable
        
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm --prefix .release/ ci

      - name: Release
        id: release
        run: |
          npx --prefix .release/ semantic-release
          cat version.env
          cat version.env >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}

      - name: Tag
        run: |
          version=${{steps.release.outputs.version}}
          
          git checkout $version
          git tag stable --force
          git push --tags --force
