name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@78e5f2ddc08efcb88fbbee6cfa3fed770ba550c3 # v1
        id: app-token
        with:
          app-id: ${{ vars.GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.GET_TOKEN_APP_PRIVATE_KEY }}
      # bootstrap-sha and release-as needs to be removed after first release
      - name: Release
        uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4
        with:
          release-type: python
          token: ${{ steps.app-token.outputs.token }}
          include-v-in-tag: false
          pull-request-header: ''
