on:
  workflow_call:
    secrets:
      TFLINT_AWS_REGION:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World 1!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "x - ${{ vars.GET_TOKEN_APP_ID }} - x"
