---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform: [1.0.0, latest]
        directories: [".", "examples/cost", "examples/simple", "examples/full"]
    defaults:
      run:
        working-directory: ${{ matrix.directories }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ matrix.terraform }}

      - run: terraform init -input=false -backend=false

      - run: terraform validate
