---
name: XXX

on: # yamllint disable-line rule:truthy
  push:

jobs:
  xxx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.GET_TOKEN_APP_PRIVATE_KEY }}
