name: Update Release Branch

on:
  push:
    branches:
      - release-please--branches--main

jobs:
  terraform-docs:
    name: Update terraform docs in README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          find-dir: .
          git-commit-message: "docs: update Terraform docs"
          git-push: true

  terraform-format-push:
    name: Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -write=true -recursive
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: "chore: format Terraform code"
