name: Update Release Branch

on:
  push:
    branches:
      - release-please--branches--main

jobs:
  terraform-docs:
    name: Update terraform docs in README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
        with:
          find-dir: .
          git-commit-message: "docs: update Terraform docs"
          git-push: true

  terraform-format-push:
    name: Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -write=true -recursive
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: "chore: format Terraform code"
