name: Update Release Branch

on:
  push:
    branches:
      - release-please--branches--main

jobs:
  terraform-docs:
    name: Update terraform docs in README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          find-dir: .
          git-commit-message: "docs: update Terraform docs"
          git-push: true

  terraform-format-push:
    name: Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -write=true -recursive
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        with:
          commit_message: "chore: format Terraform code"
